/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Danni
 */
public class ViewSales extends javax.swing.JPanel {

    /**
     * Creates new form ViewSales
     */
    public ViewSales() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jl_seller = new javax.swing.JLabel();
        jl_date = new javax.swing.JLabel();
        jl_dateFormat = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jl_customer = new javax.swing.JLabel();
        jl_rfc = new javax.swing.JLabel();
        jl_idCustomer = new javax.swing.JLabel();
        jl_idProduct = new javax.swing.JLabel();
        jtf_idProduct = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jbtn_searchProduct = new javax.swing.JButton();
        jl_idSeller = new javax.swing.JLabel();
        jbtn_searchByName = new javax.swing.JButton();
        jl_sellerName = new javax.swing.JLabel();
        jl_idSeller1 = new javax.swing.JLabel();
        jl_idCustomer1 = new javax.swing.JLabel();
        jl_customer1 = new javax.swing.JLabel();
        jl_rfc1 = new javax.swing.JLabel();
        jbtn_back = new javax.swing.JButton();
        jbtn_cancelSale = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_sale = new javax.swing.JTable();
        jbtn_newSale = new javax.swing.JButton();
        jtf_total = new javax.swing.JTextField();
        jtf_totalN = new javax.swing.JTextField();
        jtf_taxes = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jp_size = new javax.swing.JPanel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jPanel1.setForeground(new java.awt.Color(204, 255, 204));

        jl_seller.setText("Vendedor:");

        jl_date.setText("Fecha:");

        jl_dateFormat.setText("DD/MM/AAAA");

        jl_customer.setText("Cliente:");

        jl_rfc.setText("RFC:");

        jl_idCustomer.setText("Clave Cliente:");

        jl_idProduct.setText("ID:");

        jbtn_searchProduct.setText("Agregar");

        jl_idSeller.setText("ID:");

        jbtn_searchByName.setText("Nombre");

        jl_sellerName.setText("Vendedor");

        jl_idSeller1.setText("ID:");

        jl_idCustomer1.setText("ID:");

        jl_customer1.setText("Cliente:");

        jl_rfc1.setText("RFC:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jl_date)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_dateFormat))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jl_seller)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_sellerName, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jl_idSeller)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jl_idSeller1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jl_idProduct)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jtf_idProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbtn_searchProduct)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jbtn_searchByName))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jl_customer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jl_customer1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jl_idCustomer)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jl_idCustomer1, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jl_rfc)
                        .addGap(18, 18, 18)
                        .addComponent(jl_rfc1)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jl_idSeller)
                        .addComponent(jl_idSeller1))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jl_seller)
                        .addComponent(jl_sellerName)))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_date)
                    .addComponent(jl_dateFormat))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_idCustomer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jl_idCustomer1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_customer)
                    .addComponent(jl_customer1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jl_rfc)
                    .addComponent(jl_rfc1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtf_idProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jl_idProduct)
                    .addComponent(jbtn_searchByName)
                    .addComponent(jbtn_searchProduct))
                .addGap(39, 39, 39))
        );

        add(jPanel1);
        jPanel1.setBounds(50, 110, 300, 200);

        jbtn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/regresar.png"))); // NOI18N
        jbtn_back.setBorder(null);
        jbtn_back.setBorderPainted(false);
        jbtn_back.setContentAreaFilled(false);
        jbtn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_back.setDefaultCapable(false);
        add(jbtn_back);
        jbtn_back.setBounds(50, 30, 50, 50);

        jbtn_cancelSale.setText("Cancelar Venta");
        add(jbtn_cancelSale);
        jbtn_cancelSale.setBounds(420, 160, 130, 30);

        jt_sale.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jt_sale.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Precio", "Cantidad", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jt_sale);

        add(jScrollPane1);
        jScrollPane1.setBounds(40, 370, 530, 110);

        jbtn_newSale.setText("Nueva Venta");
        add(jbtn_newSale);
        jbtn_newSale.setBounds(420, 120, 130, 30);
        add(jtf_total);
        jtf_total.setBounds(80, 330, 60, 20);
        add(jtf_totalN);
        jtf_totalN.setBounds(330, 330, 70, 20);
        add(jtf_taxes);
        jtf_taxes.setBounds(180, 330, 70, 20);

        jLabel13.setText("TOTAL NETO:");
        add(jLabel13);
        jLabel13.setBounds(260, 330, 70, 20);

        jLabel4.setText("IVA:");
        add(jLabel4);
        jLabel4.setBounds(150, 330, 30, 20);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/generatedtext (4).png"))); // NOI18N
        add(jLabel2);
        jLabel2.setBounds(130, 0, 380, 100);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Comic-Hulk-Dibujo - copia.jpg"))); // NOI18N
        add(jLabel10);
        jLabel10.setBounds(90, 70, 770, 520);

        jLabel12.setText("TOTAL:");
        add(jLabel12);
        jLabel12.setBounds(40, 330, 50, 20);

        jp_size.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jp_sizeLayout = new javax.swing.GroupLayout(jp_size);
        jp_size.setLayout(jp_sizeLayout);
        jp_sizeLayout.setHorizontalGroup(
            jp_sizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 690, Short.MAX_VALUE)
        );
        jp_sizeLayout.setVerticalGroup(
            jp_sizeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 580, Short.MAX_VALUE)
        );

        add(jp_size);
        jp_size.setBounds(0, 0, 690, 580);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    public javax.swing.JButton jbtn_back;
    public javax.swing.JButton jbtn_cancelSale;
    public javax.swing.JButton jbtn_newSale;
    public javax.swing.JButton jbtn_searchByName;
    public javax.swing.JButton jbtn_searchProduct;
    public javax.swing.JLabel jl_customer;
    public javax.swing.JLabel jl_customer1;
    public javax.swing.JLabel jl_date;
    public javax.swing.JLabel jl_dateFormat;
    private javax.swing.JLabel jl_idCustomer;
    public javax.swing.JLabel jl_idCustomer1;
    private javax.swing.JLabel jl_idProduct;
    private javax.swing.JLabel jl_idSeller;
    public javax.swing.JLabel jl_idSeller1;
    public javax.swing.JLabel jl_rfc;
    public javax.swing.JLabel jl_rfc1;
    public javax.swing.JLabel jl_seller;
    public javax.swing.JLabel jl_sellerName;
    public javax.swing.JPanel jp_size;
    public javax.swing.JTable jt_sale;
    public javax.swing.JTextField jtf_idProduct;
    public javax.swing.JTextField jtf_taxes;
    public javax.swing.JTextField jtf_total;
    public javax.swing.JTextField jtf_totalN;
    // End of variables declaration//GEN-END:variables
}
