/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Diego
 */
public class ViewNewProducts extends javax.swing.JPanel {

    /**
     * Creates new form ViewProductsT
     */
    public ViewNewProducts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtf_idProducto = new javax.swing.JTextField();
        jtf_producto = new javax.swing.JTextField();
        jtf_precioCompra = new javax.swing.JTextField();
        jtf_precioVenta = new javax.swing.JTextField();
        jtf_existencias = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbtn_save = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jta_descripcion = new javax.swing.JTextArea();
        jl_background = new javax.swing.JLabel();
        jp_size = new javax.swing.JPanel();

        setBackground(new java.awt.Color(153, 153, 255));
        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Datos del producto");
        add(jLabel1);
        jLabel1.setBounds(117, 11, 150, 22);

        jtf_idProducto.setEditable(false);
        add(jtf_idProducto);
        jtf_idProducto.setBounds(140, 70, 43, 20);

        jtf_producto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_productoActionPerformed(evt);
            }
        });
        add(jtf_producto);
        jtf_producto.setBounds(100, 120, 96, 20);
        add(jtf_precioCompra);
        jtf_precioCompra.setBounds(350, 70, 56, 20);
        add(jtf_precioVenta);
        jtf_precioVenta.setBounds(350, 120, 56, 20);
        add(jtf_existencias);
        jtf_existencias.setBounds(370, 230, 53, 20);

        jLabel2.setText("id_producto:");
        add(jLabel2);
        jLabel2.setBounds(20, 70, 90, 14);

        jLabel3.setText("Producto");
        add(jLabel3);
        jLabel3.setBounds(20, 120, 60, 14);

        jLabel4.setText("Descripcion");
        add(jLabel4);
        jLabel4.setBounds(14, 150, 110, 14);

        jLabel5.setText("Precio Compra");
        add(jLabel5);
        jLabel5.setBounds(250, 70, 130, 14);

        jLabel6.setText("Precio Venta");
        add(jLabel6);
        jLabel6.setBounds(260, 130, 130, 14);

        jLabel7.setText("Existencias");
        add(jLabel7);
        jLabel7.setBounds(300, 230, 80, 14);

        jbtn_save.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/guardar.png"))); // NOI18N
        jbtn_save.setBorder(null);
        jbtn_save.setBorderPainted(false);
        jbtn_save.setContentAreaFilled(false);
        jbtn_save.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_saveActionPerformed(evt);
            }
        });
        add(jbtn_save);
        jbtn_save.setBounds(350, 300, 50, 50);

        jta_descripcion.setColumns(20);
        jta_descripcion.setRows(5);
        jScrollPane1.setViewportView(jta_descripcion);

        add(jScrollPane1);
        jScrollPane1.setBounds(20, 170, 240, 210);

        jl_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/produs2.jpg"))); // NOI18N
        jl_background.setText("jLabel8");
        add(jl_background);
        jl_background.setBounds(-180, 0, 960, 450);
        add(jp_size);
        jp_size.setBounds(0, 0, 770, 450);
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_productoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_productoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_productoActionPerformed

    private void jbtn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_saveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_saveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtn_save;
    private javax.swing.JLabel jl_background;
    private javax.swing.JPanel jp_size;
    public javax.swing.JTextArea jta_descripcion;
    public javax.swing.JTextField jtf_existencias;
    public javax.swing.JTextField jtf_idProducto;
    public javax.swing.JTextField jtf_precioCompra;
    public javax.swing.JTextField jtf_precioVenta;
    public javax.swing.JTextField jtf_producto;
    // End of variables declaration//GEN-END:variables
}
