/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;


import javax.swing.table.DefaultTableModel;
import jdda.ConnectionDB;

/**
 *
 * @author panda
 */
public class ViewCustomers extends javax.swing.JFrame {
  /*  
    private DefaultTableModel model;
    ConnectionDB con = new ConnectionDB();
*/
    /**
     * Creates new form ViewCustomers
     */
    public ViewCustomers() {
        initComponents();
    }
    /*
        public void carfarInterface(){
        String data[][] = {};
        String col[] = {"ID","Nombre","Apellido P","Apellido M","Contacto","Tel.","email"};
        
        model = new DefaultTableModel(data, col);
        jt_infoCustomer.setModel(model);
    }
*/
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jbtn_edit = new javax.swing.JButton();
        jbtn_delete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_infoCustomer = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_search = new javax.swing.JMenu();
        jmi_byID = new javax.swing.JMenuItem();
        jmi_byName = new javax.swing.JMenuItem();
        jmi_byState = new javax.swing.JMenuItem();
        jmi_byNick = new javax.swing.JMenuItem();
        jm_add = new javax.swing.JMenu();
        jmi_newCustomer = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(0, 51, 204));
        jPanel2.setForeground(new java.awt.Color(255, 51, 51));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Impact", 0, 18)); // NOI18N
        jLabel4.setText("Infromación existente: ");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 140, 210, 23);

        jbtn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-validated_40458.png"))); // NOI18N
        jbtn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_editActionPerformed(evt);
            }
        });
        jPanel2.add(jbtn_edit);
        jbtn_edit.setBounds(140, 350, 80, 60);

        jbtn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Borrar_trituradora.png"))); // NOI18N
        jPanel2.add(jbtn_delete);
        jbtn_delete.setBounds(50, 350, 83, 59);

        jt_infoCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jt_infoCustomer);

        jPanel2.add(jScrollPane2);
        jScrollPane2.setBounds(10, 180, 440, 150);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/generatedtext.png"))); // NOI18N
        jPanel2.add(jLabel1);
        jLabel1.setBounds(-30, 20, 460, 80);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/robin-batman-dc-comics-superhero-pics-161649.jpg"))); // NOI18N
        jPanel2.add(jLabel2);
        jLabel2.setBounds(-10, 0, 670, 500);

        jm_search.setText("Buscar");

        jmi_byID.setText("Por Número...");
        jm_search.add(jmi_byID);

        jmi_byName.setText("Por Nombre...");
        jm_search.add(jmi_byName);

        jmi_byState.setText("Por Estado...");
        jm_search.add(jmi_byState);

        jmi_byNick.setText("Por Nombre de Contacto...");
        jm_search.add(jmi_byNick);

        jMenuBar1.add(jm_search);

        jm_add.setText("Nuevo");

        jmi_newCustomer.setText("Cliente...");
        jm_add.add(jmi_newCustomer);

        jMenuBar1.add(jm_add);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 459, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
  //      carfarInterface();
        //con.basicConsult("clientes", "id_cliente", "1");
        
    //    model.setValueAt(con.getColumn()[3], 2, 2);
    }//GEN-LAST:event_formWindowActivated

    private void jbtn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCustomers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCustomers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel4;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JButton jbtn_delete;
    public javax.swing.JButton jbtn_edit;
    public javax.swing.JMenu jm_add;
    public javax.swing.JMenu jm_search;
    public javax.swing.JMenuItem jmi_byID;
    public javax.swing.JMenuItem jmi_byName;
    public javax.swing.JMenuItem jmi_byNick;
    public javax.swing.JMenuItem jmi_byState;
    public javax.swing.JMenuItem jmi_newCustomer;
    public javax.swing.JTable jt_infoCustomer;
    // End of variables declaration//GEN-END:variables
}
