/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Diego
 */
public class ViewEditProducts extends javax.swing.JPanel {

    /**
     * Creates new form ViewEdit
     */
    public ViewEditProducts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtf_idProductoe = new javax.swing.JTextField();
        jtf_productoe = new javax.swing.JTextField();
        jtf_precioComprae = new javax.swing.JTextField();
        jtf_precioVentae = new javax.swing.JTextField();
        jtf_existenciase = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jbtn_savee = new javax.swing.JButton();
        jta_descripcione = new javax.swing.JTextArea();
        jScrollPane1 = new javax.swing.JScrollPane();
        jLabel9 = new javax.swing.JLabel();

        setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Datos del producto");
        add(jLabel1);
        jLabel1.setBounds(280, 10, 150, 22);

        jtf_idProductoe.setEditable(false);
        add(jtf_idProductoe);
        jtf_idProductoe.setBounds(260, 90, 43, 20);

        jtf_productoe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_productoeActionPerformed(evt);
            }
        });
        add(jtf_productoe);
        jtf_productoe.setBounds(260, 140, 96, 20);
        add(jtf_precioComprae);
        jtf_precioComprae.setBounds(520, 80, 56, 20);
        add(jtf_precioVentae);
        jtf_precioVentae.setBounds(520, 140, 56, 20);
        add(jtf_existenciase);
        jtf_existenciase.setBounds(420, 190, 53, 20);

        jLabel2.setText("id_producto:");
        add(jLabel2);
        jLabel2.setBounds(190, 90, 90, 14);

        jLabel3.setText("Producto");
        add(jLabel3);
        jLabel3.setBounds(190, 140, 60, 14);

        jLabel4.setText("Descripcion");
        add(jLabel4);
        jLabel4.setBounds(220, 240, 110, 14);

        jLabel5.setText("Precio Compra");
        add(jLabel5);
        jLabel5.setBounds(420, 80, 130, 14);

        jLabel6.setText("Precio Venta");
        add(jLabel6);
        jLabel6.setBounds(420, 140, 130, 14);

        jLabel7.setText("Existencias");
        add(jLabel7);
        jLabel7.setBounds(340, 200, 80, 14);

        jbtn_savee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/guardar.png"))); // NOI18N
        jbtn_savee.setBorder(null);
        jbtn_savee.setBorderPainted(false);
        jbtn_savee.setContentAreaFilled(false);
        jbtn_savee.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_savee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_saveeActionPerformed(evt);
            }
        });
        add(jbtn_savee);
        jbtn_savee.setBounds(50, 160, 50, 50);

        jta_descripcione.setColumns(20);
        jta_descripcione.setRows(5);
        jta_descripcione.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        add(jta_descripcione);
        jta_descripcione.setBounds(220, 260, 380, 208);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/productsEdit2.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        jScrollPane1.setViewportView(jLabel9);

        add(jScrollPane1);
        jScrollPane1.setBounds(0, 0, 980, 500);
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_productoeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_productoeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_productoeActionPerformed

    private void jbtn_saveeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_saveeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_saveeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtn_savee;
    public javax.swing.JTextArea jta_descripcione;
    public javax.swing.JTextField jtf_existenciase;
    public javax.swing.JTextField jtf_idProductoe;
    public javax.swing.JTextField jtf_precioComprae;
    public javax.swing.JTextField jtf_precioVentae;
    public javax.swing.JTextField jtf_productoe;
    // End of variables declaration//GEN-END:variables
}
