/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author panda
 */
public class ViewProducts extends javax.swing.JFrame {

    /**
     * Creates new form ViewProducts
     */
    public ViewProducts() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_BackGround = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jbtn_borrar = new javax.swing.JButton();
        jbtn_edit = new javax.swing.JButton();
        jbtn_back = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jbtn_actualizar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_productos = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jm_buscar = new javax.swing.JMenu();
        jmi_noProducto = new javax.swing.JMenuItem();
        jmi_nombreProducto = new javax.swing.JMenuItem();
        jmi_descricionProducto = new javax.swing.JMenuItem();
        jm_agregar = new javax.swing.JMenu();
        jmi_nuevoProducto = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 51, 255));

        jp_BackGround.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Productos");
        jp_BackGround.add(jLabel1);
        jLabel1.setBounds(210, 20, 230, 56);

        jbtn_borrar.setFont(new java.awt.Font("BankGothic Md BT", 0, 11)); // NOI18N
        jbtn_borrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Borrar_trituradora.png"))); // NOI18N
        jbtn_borrar.setText("BORRAR");
        jbtn_borrar.setBorder(null);
        jbtn_borrar.setBorderPainted(false);
        jbtn_borrar.setContentAreaFilled(false);
        jbtn_borrar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_borrar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_borrarActionPerformed(evt);
            }
        });
        jp_BackGround.add(jbtn_borrar);
        jbtn_borrar.setBounds(70, 350, 80, 80);

        jbtn_edit.setFont(new java.awt.Font("BankGothic Md BT", 0, 11)); // NOI18N
        jbtn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-validated_40458.png"))); // NOI18N
        jbtn_edit.setText("EDITAR");
        jbtn_edit.setBorder(null);
        jbtn_edit.setBorderPainted(false);
        jbtn_edit.setContentAreaFilled(false);
        jbtn_edit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_edit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jbtn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_editActionPerformed(evt);
            }
        });
        jp_BackGround.add(jbtn_edit);
        jbtn_edit.setBounds(180, 350, 80, 80);

        jbtn_back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/regresar.png"))); // NOI18N
        jbtn_back.setBorder(null);
        jbtn_back.setBorderPainted(false);
        jbtn_back.setContentAreaFilled(false);
        jbtn_back.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jbtn_back.setDefaultCapable(false);
        jp_BackGround.add(jbtn_back);
        jbtn_back.setBounds(50, 30, 50, 50);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Informacion exisente:");
        jp_BackGround.add(jLabel3);
        jLabel3.setBounds(30, 94, 220, 30);

        jbtn_actualizar.setFont(new java.awt.Font("Bookman Old Style", 0, 11)); // NOI18N
        jbtn_actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/button-refresh-29881.jpg"))); // NOI18N
        jbtn_actualizar.setText("ACTUALIZAR");
        jbtn_actualizar.setBorder(null);
        jbtn_actualizar.setBorderPainted(false);
        jbtn_actualizar.setContentAreaFilled(false);
        jbtn_actualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jbtn_actualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jp_BackGround.add(jbtn_actualizar);
        jbtn_actualizar.setBounds(300, 350, 80, 80);

        jt_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Productos", "Descripción", "Precio Venta", "Precio Compra", "Existencia"
            }
        ));
        jScrollPane1.setViewportView(jt_productos);

        jp_BackGround.add(jScrollPane1);
        jScrollPane1.setBounds(20, 140, 470, 190);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/products.jpg"))); // NOI18N
        jp_BackGround.add(jLabel2);
        jLabel2.setBounds(0, -40, 770, 510);

        jm_buscar.setText("Buscar");

        jmi_noProducto.setText("No. del producto");
        jm_buscar.add(jmi_noProducto);

        jmi_nombreProducto.setText("Nombre del producto");
        jm_buscar.add(jmi_nombreProducto);

        jmi_descricionProducto.setText("Descripcion del producto");
        jm_buscar.add(jmi_descricionProducto);

        jMenuBar1.add(jm_buscar);

        jm_agregar.setText("Agregar");

        jmi_nuevoProducto.setText("Nuevo Producto");
        jm_agregar.add(jmi_nuevoProducto);

        jMenuBar1.add(jm_agregar);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 770, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jp_BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, 770, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 437, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jp_BackGround, javax.swing.GroupLayout.PREFERRED_SIZE, 431, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_borrarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_borrarActionPerformed

    private void jbtn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JButton jbtn_actualizar;
    public javax.swing.JButton jbtn_back;
    public javax.swing.JButton jbtn_borrar;
    public javax.swing.JButton jbtn_edit;
    public javax.swing.JMenu jm_agregar;
    public javax.swing.JMenu jm_buscar;
    public javax.swing.JMenuItem jmi_descricionProducto;
    public javax.swing.JMenuItem jmi_noProducto;
    public javax.swing.JMenuItem jmi_nombreProducto;
    public javax.swing.JMenuItem jmi_nuevoProducto;
    public javax.swing.JPanel jp_BackGround;
    public javax.swing.JTable jt_productos;
    // End of variables declaration//GEN-END:variables
}
