/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Danni
 */
public class ViewEditCustomers extends javax.swing.JPanel {

    /**
     * Creates new form ViewEditCustomer
     */
    public ViewEditCustomers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtf_name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtf_lastNameP = new javax.swing.JTextField();
        jtf_lastNameM = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jtf_no = new javax.swing.JTextField();
        jtf_city = new javax.swing.JTextField();
        jtf_suburb = new javax.swing.JTextField();
        jtf_street = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jtf_tNumber = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jtf_email = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jtf_nick = new javax.swing.JTextField();
        jbtn_accept = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jcb_states = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 51, 204));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel1.setText("Nombre(s):");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 110, 75, 19);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setText("Apellido Pat.");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(170, 110, 87, 19);

        jtf_name.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(jtf_name);
        jtf_name.setBounds(20, 130, 140, 25);

        jLabel3.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel3.setText("Apellido Mat.");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(320, 110, 92, 19);

        jtf_lastNameP.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(jtf_lastNameP);
        jtf_lastNameP.setBounds(170, 130, 140, 25);

        jtf_lastNameM.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(jtf_lastNameM);
        jtf_lastNameM.setBounds(320, 130, 130, 25);

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel4.setText("Dirección:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(170, 230, 130, 31);

        jLabel6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel6.setText("Calle:");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(30, 270, 41, 19);

        jLabel7.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel7.setText("Colonia: ");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(30, 300, 62, 19);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setText("Ciudad:");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(270, 300, 54, 19);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        jLabel9.setText("Estado:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(30, 370, 70, 23);

        jLabel10.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel10.setText("No.");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(310, 270, 23, 19);

        jtf_no.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(jtf_no);
        jtf_no.setBounds(340, 270, 88, 25);

        jtf_city.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(jtf_city);
        jtf_city.setBounds(340, 300, 88, 25);

        jtf_suburb.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(jtf_suburb);
        jtf_suburb.setBounds(92, 300, 120, 25);

        jtf_street.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(jtf_street);
        jtf_street.setBounds(92, 270, 120, 25);

        jLabel11.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel11.setText("Telefono:");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 160, 62, 19);

        jtf_tNumber.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(jtf_tNumber);
        jtf_tNumber.setBounds(120, 160, 103, 25);

        jLabel12.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel12.setText("e-mail:");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(240, 160, 50, 19);

        jtf_email.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jPanel1.add(jtf_email);
        jtf_email.setBounds(290, 160, 160, 25);

        jLabel13.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel13.setText("Nombre de Contacto:");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(20, 200, 148, 19);

        jtf_nick.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jtf_nick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_nickActionPerformed(evt);
            }
        });
        jPanel1.add(jtf_nick);
        jtf_nick.setBounds(170, 200, 280, 25);

        jbtn_accept.setBackground(new java.awt.Color(255, 255, 255));
        jbtn_accept.setFont(new java.awt.Font("Century Gothic", 0, 14)); // NOI18N
        jbtn_accept.setText("Aceptar");
        jPanel1.add(jbtn_accept);
        jbtn_accept.setBounds(230, 340, 192, 68);

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/generatedtext (2).png"))); // NOI18N
        jPanel1.add(jLabel15);
        jLabel15.setBounds(60, 0, 320, 120);

        jcb_states.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Aguascalientes", "Baja California", "Baja California Sur", "Campeche", "CDMX", "Coahuila", "Colima", "Chiapas", "Chihuahua", "Durango", "Guanajuato", "Guerrero", "Hidalgo", "Jalisco", "México", "Michoacán", "Morelos", "Nayarit", "Nuevo León", "Oaxaca", "Puebla", "Querétaro", "Quintana Roo", "San Luis Potosí", "Sinaloa", "Sonora", "Tabasco", "Tamaulipas", "Tlaxcala", "Veracruz", "Yucatán", "Zacatecas" }));
        jPanel1.add(jcb_states);
        jcb_states.setBounds(110, 370, 106, 30);

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/16047575-duotone-red-yellow-pop-art-polka-dot-dotted-pattern.jpg"))); // NOI18N
        jPanel1.add(jLabel14);
        jLabel14.setBounds(0, -80, 560, 570);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_nickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_nickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_nickActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JButton jbtn_accept;
    public javax.swing.JComboBox<String> jcb_states;
    public javax.swing.JTextField jtf_city;
    public javax.swing.JTextField jtf_email;
    public javax.swing.JTextField jtf_lastNameM;
    public javax.swing.JTextField jtf_lastNameP;
    public javax.swing.JTextField jtf_name;
    public javax.swing.JTextField jtf_nick;
    public javax.swing.JTextField jtf_no;
    public javax.swing.JTextField jtf_street;
    public javax.swing.JTextField jtf_suburb;
    public javax.swing.JTextField jtf_tNumber;
    // End of variables declaration//GEN-END:variables
}
