/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

/**
 *
 * @author Raúl
 */
public class ViewSuppliers extends javax.swing.JFrame {

    /**
     * Creates new form ViewSuppliersBeta
     */
    public ViewSuppliers() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jp_barckGround = new javax.swing.JPanel();
        jl_title = new javax.swing.JLabel();
        jsc_table = new javax.swing.JScrollPane();
        jt_suppliers = new javax.swing.JTable();
        jbtn_edit = new javax.swing.JButton();
        jbtn_delete = new javax.swing.JButton();
        jl_backGround = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jmi_id = new javax.swing.JMenuItem();
        jmi_name = new javax.swing.JMenuItem();
        jmi_RFC = new javax.swing.JMenuItem();
        jmi_streed = new javax.swing.JMenuItem();
        jmi_hood = new javax.swing.JMenuItem();
        jmi_city = new javax.swing.JMenuItem();
        jmi_state = new javax.swing.JMenuItem();
        jmi_contact = new javax.swing.JMenuItem();
        jmi_phone = new javax.swing.JMenuItem();
        jmi_email = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmi_add = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jmi_main = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jp_barckGround.setLayout(null);

        jl_title.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        jl_title.setForeground(new java.awt.Color(0, 102, 102));
        jl_title.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/title_suppliers.png"))); // NOI18N
        jp_barckGround.add(jl_title);
        jl_title.setBounds(70, 0, 420, 110);

        jt_suppliers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nombre", "RFC", "Calle", "Colonia", "Ciudad", "Estado", "Contacto", "Telefono", "E-mail"
            }
        ));
        jsc_table.setViewportView(jt_suppliers);

        jp_barckGround.add(jsc_table);
        jsc_table.setBounds(0, 110, 520, 190);

        jbtn_edit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/edit-validated_40458.png"))); // NOI18N
        jbtn_edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtn_editActionPerformed(evt);
            }
        });
        jp_barckGround.add(jbtn_edit);
        jbtn_edit.setBounds(290, 300, 80, 60);

        jbtn_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Borrar_trituradora.png"))); // NOI18N
        jp_barckGround.add(jbtn_delete);
        jbtn_delete.setBounds(120, 300, 83, 59);

        jl_backGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/suppliers.jpg"))); // NOI18N
        jl_backGround.setText("jLabel1");
        jp_barckGround.add(jl_backGround);
        jl_backGround.setBounds(0, 0, 600, 360);

        jMenu1.setText("Buscar");

        jmi_id.setText("Por id");
        jMenu1.add(jmi_id);

        jmi_name.setText("Por Nombre");
        jMenu1.add(jmi_name);

        jmi_RFC.setText("Por RFC");
        jMenu1.add(jmi_RFC);

        jmi_streed.setText("Por Calle");
        jMenu1.add(jmi_streed);

        jmi_hood.setText("Por Colonia");
        jMenu1.add(jmi_hood);

        jmi_city.setText("Por Ciudad");
        jMenu1.add(jmi_city);

        jmi_state.setText("Por Estado");
        jMenu1.add(jmi_state);

        jmi_contact.setText("Por Contacto");
        jMenu1.add(jmi_contact);

        jmi_phone.setText("Por telefono");
        jMenu1.add(jmi_phone);

        jmi_email.setText("Por e-mail");
        jMenu1.add(jmi_email);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Agregar");

        jmi_add.setText("Nuevo Proveedor");
        jMenu2.add(jmi_add);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Revision");

        jmi_main.setText("Principal");
        jmi_main.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_mainActionPerformed(evt);
            }
        });
        jMenu3.add(jmi_main);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_barckGround, javax.swing.GroupLayout.PREFERRED_SIZE, 601, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jp_barckGround, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmi_mainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_mainActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jmi_mainActionPerformed

    private void jbtn_editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtn_editActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jbtn_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewSuppliers.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewSuppliers().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenu jMenu1;
    public javax.swing.JMenu jMenu2;
    public javax.swing.JMenu jMenu3;
    public javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JButton jbtn_delete;
    public javax.swing.JButton jbtn_edit;
    public javax.swing.JLabel jl_backGround;
    public javax.swing.JLabel jl_title;
    public javax.swing.JMenuItem jmi_RFC;
    public javax.swing.JMenuItem jmi_add;
    public javax.swing.JMenuItem jmi_city;
    public javax.swing.JMenuItem jmi_contact;
    public javax.swing.JMenuItem jmi_email;
    public javax.swing.JMenuItem jmi_hood;
    public javax.swing.JMenuItem jmi_id;
    public javax.swing.JMenuItem jmi_main;
    public javax.swing.JMenuItem jmi_name;
    public javax.swing.JMenuItem jmi_phone;
    public javax.swing.JMenuItem jmi_state;
    public javax.swing.JMenuItem jmi_streed;
    public javax.swing.JPanel jp_barckGround;
    public javax.swing.JScrollPane jsc_table;
    public javax.swing.JTable jt_suppliers;
    // End of variables declaration//GEN-END:variables
}
